agents_file: .codegpt/agents.yaml
references:
  - AGENTS.md
modules:

  - name: mobile-app-core
    path: mobile-app/src
    tags: [mobile, react-native, redux, navigation, core]
    include:
      - "App.tsx"
      - "store/**/*.ts"
      - "navigation/**/*.tsx"

  - name: mobile-app-screens
    path: mobile-app/src/screens
    tags: [mobile, screens, ui, components]
    include:
      - "**/*.tsx"

  - name: mobile-app-services
    path: mobile-app/src/services
    tags: [mobile, services, api, business-logic]
    include:
      - "**/*.ts"

  - name: backend-handlers
    path: backend/src/handlers
    tags: [backend, lambda, serverless, api]
    include:
      - "**/*.js"

  - name: backend-utils
    path: backend/src/utils
    tags: [backend, utilities, helpers]
    include:
      - "**/*.js"
    references:
        - .codegpt/agents.yaml

  - name: mobile-app-config
    path: mobile-app/
    tags: [config, amplify, expo, aws]
    include:
      - "*.json"
      - "*.js"
      - "amplify/**"
      - "aws-exports.js"
      - "amplifyconfiguration.json"
      - ".env.example"
      - "amplify-v6-complete-fix.js"
      - "amplify-migrator-pro.js"
      - "polyfills/**/*.ts"

  - name: graphql-api
    path: mobile-app/src/graphql
    tags: [graphql, api, queries, mutations]
    include:
      - "**/*.ts"

  - name: slices
    path: mobile-app/src/store/slices
    tags: [redux, slices, state-management, thunk, typescript]
    include:
      - "**/*.ts"

  - name: amplify-schemas
    path: mobile-app/amplify/backend/api/boatrentalapp
    tags: [amplify, graphql, schema]
    include:
      - "*.graphql"

  - name: shared-types
    path: mobile-app/src/types
    tags: [types, shared, api]
    include:
      - "**/*.ts"

  - name: config-files
    path: mobile-app/
    tags: [config, json, env]
    include:
    - "*.json"
    - ".env.example"
    - "tsconfig.json"
    - "babel.config.js"
    - "metro.config.js"
